### ISSUE TITLE
SL Review: Decisions on Distributing SL review form

### ISSUE THREAD

**Issue by fazil-ey** [alexandralloyd/DJ-program#17]
The scope has changed with the new ADM-led process. 

Questions to be answered - 
1. Who owns the distribution of the SL review form to all ADMs that need to have access to the form? 
    - How will it be distributed? 
2. Who owns the communication - sending reminders for deadlines or other announcements during the SL review process? 

---------------------

Once the Senior Leader Review form is complete & we are ready to start the SL review process, we need to distribute the form to all the senior leaders. 

The following decisions need to be made before we can do that - 

1. Who owns the distribution of the SL review form to all Senior leaders that need to have access to the form? 
    - Is the Digital Journey Team responsible for distributing it to the Band 5/6 & nominated Band 4 employees? 
    - Will the digital journey team provide the link/URL and the SHR teams in each ministry will be responsible for distributing it in their teams? 
    - Is there another team that will coordinate this? If so, how? 
2. Who owns the communication - sending reminders for deadlines or other announcements during the SL review process? 
3. How will the communication happen? 
   - Emails?
   - Page in a myHR? 
4. Will the link to form directly take SLs to the form? How would they submit a new form if they have to?

**Comment by MeghanStothers** [comment]
The SL team to connect with PIE (Andrea Gillis) to work on a communications plan that will include tactics about how/when/where to distribute the link and key messages to senior leaders (target audience).
