### ISSUE TITLE
SL Review - Copy for Section "About the review process" 

### ISSUE THREAD

**Issue by fazil-ey** [alexandralloyd/DJ-program#19]
We need copy for the "About the review process" for Senior Leaders to understand the SL review process

Notes from UX Sessions- 
1. Time/deadlines
2. Encouraging people to consult people who have worked closely with the senior leader or  to have a conversation with the senior leader
3. The process and how the form will be used
4. Feedback from telework has been that too much text in the form can be overwhelming. An idea to address this is to add links to pages for more detailed information

**Comment by JodiLittle** [comment]
Draft to be ready by end of the day Sept 29.

**Comment by HasanSifat** [comment]
Copy recieved
