### ISSUE TITLE
SL Review - Copy for Miscellaneous Tooltips/Descriptions/Copy

### ISSUE THREAD

**Issue by fazil-ey** [alexandralloyd/DJ-program#21]
We need copy for the following fields/section
- [x] Section description for "Select Senior Leader" to make it clear they they have to search for the leader they want to nominate & use the basic info section to check if the person they selected from the list is the person they intend to nominate.
- [x] Section description for "Basic Information" to ensure people can change it. Specifically that prepopulated fields can be changed if they are not correct
- [x] For sections "Expertise & Skills" and "Learning and Development", share categorized list  of options 
- [ ] Copy for the question to confirm if they have had a conversation with the senior leader
    - [ ] Copy for the information popup if they answer no, saying it is highly recommended that they have a conversation with the SL they are nominating
- [ ] Copy for confirmation page after submission (instructions about validation meeting, if it happens etc.)
- [x] Copy for email for ADMs after submission (instructions about validation meeting, if it happens etc.)

**Comment by HasanSifat** [comment]
Copy received
