### ISSUE TITLE
SL Review - Copy for Section "Before we begin"

### ISSUE THREAD

**Issue by fazil-ey** [alexandralloyd/DJ-program#23]
We need copy for "Before we begin" section to explain basic logistical information about the form. 

Information to be included (not complete) - 

1. Timeout duration
2. How to save, access saved drafts
3. How long will it take to fill the form

**Note -** We can do this towards the end once we have finalized all the features that would be going into the release.

**Comment by JodiLittle** [comment]
Draft to be finalized by end of the day Sept 29.

**Comment by HasanSifat** [comment]
copy recieved
