### ISSUE TITLE
SL Review - Decision on Validation Meeting 

### ISSUE THREAD

**Issue by fazil-ey** [alexandralloyd/DJ-program#31]
Do we need a validation meeting? 

If so - How do we record the decisions & feedback from the validation meeting? 

Decision made Sep 16 -

- ADMs accountable for how they want to present the info
    - They can print pdfs or present it on the screen during the meeting
    - They can also log in to digital journey portal & show the form online
- BI teams creates aggregate reports using spreadsheet 
   

-------------------------

Options - 
1. ADMs open up forms flow for each senior leader during the meeting and answer the question about readiness & add comments.
    - might be a lot to do during the meeting
2. Delegates decided by ADMs are given access to open up forms flow and add this data during the meeting
    - might be too difficult logistically to maintain the list of delegates and if they don't show. up on the day etc
3. ADMs/someone at the meeting records all data in an excel sheet that is later put into ODS/forms flow
4. ADMs accountable for their own notes in the meeting and are asked to go into formsflow after the meeting to fill in this info
   - we can perhaps make the default selection for readiness the same as the supervisor rating, and they only need to change, add feedback if it is different.  
5. Pen & Paper notes later transcribed into Formsflow after the meeting. 
    - might open up data security issues

**Comment by JodiLittle** [comment]
A decision has been made for each ministry to determine their own process for validation. DM could give blanket approval for anything the ADM puts forward, or might want to review nominations in the ADM/DM 1-1 meetings, or may want whole exec team to review together (or whatever process they want to put in place). Given this, the ADM can print the file or screen share it. They can take notes however they want. It will be up to them to edit the nomination form with changes/additional feedback prior to final submission. We will not need to design the form in two different stages (pre and post validation) nor will we require the system to produce a summary spreadsheet for those validation meetings (not part of our MVP).
